### ISSUE TITLE
GPU Acceleration Not Utilized.

### ISSUE THREAD

**Issue by Gunwook-Nam** [snu-micc/LocalMapper#4]
I have successfully installed the code following the provided README instructions. The code functions correctly; however, it utilizes only the CPU for computations. My system is equipped with GPU accelerators, and CUDA is properly installed. Additionally, the code is designed to leverage the GPU, and the command `torch.cuda.is_available()` returns `True`. Despite this, the computations are performed solely on the CPU.

Please provide guidance on how to ensure that the code utilizes the GPU for computations.

Thank you for your assistance.

**Comment by shuan4638** [comment]
Thanks a lot for raising this!

Indeed this package is made for CPU only for now. Since installing GPU-version pytorch and GPU-version dgl requires specifying the cuda version, I don't know whether there is an effective way to detect the cuda version of each user to guide which pytorch/dgl to install.

If you are trying to install GPU-version of LocalMapper, the following commands are suggested (assume you are using cuda 11.8)
```
pip uninstall torch
pip uninstall dgl
pip install torch -index-url https://download.pytorch.org/whl/cu118
pip install dgl -f https://data.dgl.ai/wheels/torch-2.3/cu118/repo.html
```

Please let me know if you need further help.
