### ISSUE TITLE
Question about the criteria for True and False labels in USPTO_sampled.csv

### ISSUE THREAD

**Issue by bbn2h** [snu-micc/LocalMapper#6]
Hello,

I've been exploring the USPTO_sampled.csv file under the "Comparison" section of this repository, and I noticed that it contains columns with boolean values (True/False). However, I'm having trouble understanding the exact criteria or methodology used to assign these boolean values. Could you please provide more information on how these labels were determined?

Additionally, if there is any code or documentation available that explains the process of assigning these labels, it would be extremely helpful. I believe this information could also benefit other users who might have similar questions.

Thank you in advance for your help!

**Comment by shuan4638** [comment]
As described in the paper, the correctness of AAM is evaluated via graph of reaction (CGR). The code of the evaluation is not included in this repo since it requires additional package, which is not required for LocalMapper. I recommend  using [chython](https://github.com/chython/chython) to get the CGR if you are intested in evaluating them.
